### ISSUE TITLE
Remove Submitted from all the PO statuses

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#340]
Please remove submitted from all the PO status i.e the Status should read as:

1. Draft
2. Under Review
3. Approved
4. Ordered
5. Partially Received
6. Completed
7. Closed
8. Cancelled
9. Rejected

**Comment by nevesseq** [comment]
done

**Comment by Divyagawas** [comment]
On the listing pages the status are still shown as submitted-under review, Submitted Approved, Submitted Rejected

![15](https://cloud.githubusercontent.com/assets/11714762/20295311/319fa10c-ab2a-11e6-8a4a-80163bd455de.png)

**Comment by nevesseq** [comment]
fixed
