### ISSUE TITLE
On product list page filter |The label should say 'Sort by' instead of 'tatus'

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#657]
**
![image](https://cloud.githubusercontent.com/assets/11714762/22051358/867fe0b8-dd68-11e6-892f-8ed1b6af19ab.png)
**

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Not fixed on product list, please do
![image](https://cloud.githubusercontent.com/assets/11714762/22815401/62c3dc94-ef81-11e6-8b59-7924eee8d794.png)
